insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Engineering');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Support');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Legal');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Research and Development');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Product Management');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Business Development');
insert into departments (Name) values ('Services');
insert into departments (Name) values ('Sales');
insert into departments (Name) values ('Training');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Human Resources');
insert into departments (Name) values ('Marketing');
insert into departments (Name) values ('Accounting');
insert into departments (Name) values ('Legal');
